### ISSUE TITLE
Preparation 1: Funny Stories

### ISSUE THREAD

**Issue by dykesb** [STA518-02-Fall20/community#1]
Tell a funny story of a time your teacher or professor did not understand how to use technology.

I'll start things off! In grad school when I was student teaching, I *forgot* that the projector screen was down and started circling items from the slide that I was projecting... with the dry erase marker that I was holding. Dry eraser markers erase very easily from a whiteboard, but not so much so from a projector screen 🤦 

I **always** double-check that the screen is up now.

**Comment by lapoinla** [comment]
**Every** day, one of my professors would take about *15 minutes* to figure out how to start the projector, although it was the same every time. Eventually, we would just go up and do it for him. It was a 50 minute class, so we really didn't ever get through the entire lesson.

**Comment by Lolinthea** [comment]
I **wish** I could think of one right now; but, unfortunately, one isn't coming to mind.  
*If I do I will be sure to share!*

**Comment by steinaus** [comment]
One of my professors was using a tool online to **randomly** select which student would present next, but the same few people were _always_ chosen, so he kept having to refresh the selection. This happened so much that we didn't have time for everyone to present. I've always wondered if he knew he could do the random selection **_without_** replacement.

**Comment by tagudarj** [comment]
During the first week of class, my professor had a hard time logging into his computer. He said he must have **forgot** his password. After attempting to log in (_what it felt like to be_) a million times, one of the students decided to log into the computer for him. Even by the next class period, he _still_ couldn't remember his password and took another 20 minutes until a student volunteered to log in for him, **again**.

**Comment by meganwoodw** [comment]
I had a professor who was very reluctant to use blackboard because he thought it was too complicated. This was an issue because  never knew our grades and the professor would have to send all documents out via email. **Finally**, my senior year, he started using blackboard and would just rave about how *useful* and *easy* it was.

**Comment by stoweal** [comment]
I had a teacher who could **not** figure out how to add attachments to emails. It would _always_ take at least three emails for the proper documents to finally be attached. What was so surprising was that this teacher could not figure it out even though they sent out emails several times a week.

**Comment by Ste-Drew** [comment]
Seeing as you didn't specify *which* kind of technology, I get a chance to talk about my high school drumline director and his notorious use of markers. Two mistakes are tragically noteworthy. The first is his use of permanent markers on the mini whiteboard. Permanent markers, unlike dry-erase markers, do **not** erase well. The whiteboard had to be replaced. The other incident was when there were no permanent markers to be found, so he used dry-erase markers on some sheet music. It turns out that dry-erase markers on paper **smudge**. The music was ruined, and more copies were needed.

**Comment by abbeydengler** [comment]
I had a professor that did not know how to hook his **personal laptop** up to a project so we would spend _twenty minutes_ every class period as he tried to find the right cord to connect his laptop with.

**Comment by ZackPoorman** [comment]
One of my professors always took _any_ call that he received during class and he said it was because his voicemail was full. The funny part is that the calls were always **spam**.

**Comment by stewajam98** [comment]
One time, my professor spent 20 mins trying to get the *monitors* to turn on. It took a call to the IT desk and me coming up to the computer to find out she never **turned the computer on**.

**Comment by dewittau** [comment]
Last semester after going online most of my professors used **Blackboard collaborate ultra**. One time a few weeks into this a professor couldn't get her screen to share. So she said, *"Well this really burns my biscuits"* and ended class after less than 10 minutes.

**Comment by campauel** [comment]
My mom is a professor here at Grand Valley, so not *my* teacher, but still a teacher. Before this semester started we went to campus to try to figure out the technology needed to have class in person and synchronously online at the same time. We were trying everything she might do while teaching to make sure she knew how to fix whatever problems might come up, but when she played a video the sound would echo horribly and we couldn't figure out what was wrong. It turned out, the elmo has a microphone, and it was on, and it **would not turn off**. We ended up having to forcibly mute the elmo mic from within the settings of the computer (which was really difficult to get to, because whenever you tried to navigate through the settings, it would kick you out) and even that was only a temporary solution. I don't know about funny, but it was certainly frustrating.

**Comment by AtkinsonA** [comment]
Not really technology related and I see a similar post has already been shared but I had a professor that used permanent markers on a **white board**. He didn't notice until about 10 minutes from the end of class and when he tried to erase the marker he said "Oh no, I'm in trouble". The white board was not replaced so I laughed at how smudgy it was every time I walked in the classroom. _I wonder if it's still like that._

**Comment by rodrigjd** [comment]
Back in high school I took a _CAD_ class and the first week of classes the new teacher couldn't figure out how to project his screen onto the board. As a result, for the first week of the class we had to draw on paper until he figured it out. **Overall it was a great experience and now I can sort of draw 3D shapes.**

**Comment by rudhrasd** [comment]
Last semester we were supposed to take the **final exam** at 6 pm as scheduled by the professor but the exam was never posted on the blackboard and all the students kept waiting for the link to be available. *Later we got to know that the professor schedule it for the wrong date.*

**Comment by ianfetterman** [comment]
In high school we had **smartboards** in every classroom and one time a substitute teacher started writing on the **smartboard** screen with a _sharpie_. They couldn't get it cleaned off and had to replace the board.

**Comment by goochc** [comment]
In my undergrad biology class at GV, I remember my professor struggling to keep the projector screen down. Every time she got the screen to stay down, she felt **so** accomplished. Only a few minutes later, the screen would *dramatically* fly up again, leaving us students struggling to stifle our giggles.

**Comment by AWalter725** [comment]
I am sure that there has been at least one time when one my teachers or professors did not understand how to use technology, however, I **cannot** remember an exact instance where and when it occurred. _I wish that I had more to share, but at the moment I do not have a story that comes to mind_.

**Comment by TMartin20** [comment]
During the lockdown when all classes went online, I had a **professor** who wanted to record sessions every time but it took them the first _ten minutes_ of class every time to figure out how to do it again. Not _that_ funny but I had sympathy for them trying to figure out all this new stuff and change to completely online!

**Comment by JGaldeen08** [comment]
I remember when a teacher in highschool was just learning how to use the new projectors that were attached to the computer instead of the old school overhead project which was the _worst_. I'm not sure what training they went through before we started the school year, but I didn't now a single teacher that could turn it on and get it to work properly for the **first month.** After that it seemed to go smoother, but I still laugh about it anytime I watch someone struggle with turning on a projector.
