### ISSUE TITLE
0401 Knitting Issue

### ISSUE THREAD

**Issue by setsmar** [STA518-02-Fall20/community#26]
![rquestion](https://user-images.githubusercontent.com/70547379/95117583-d2aa8e80-0716-11eb-95d0-c566d9bfe1f8.png)
At first when I tried knitting I had a parse error come up then after that it points me to this line with the error. Any help is appreciated thank you!

**Comment by dykesb** [comment]
The error says that `usa` is not found. When you see this type of error, it usually means that you did not store this object in your Rmd file.  Remember that whenever you knit, the Rmd starts from a blank slate so it will not remember anything that you currently have in your **Environment** pane unless you have also created it (i.e., assigned it `<-`) in your Rmd file. Double check that you have this in a chunk above your `Dennys and Laquinta Scatterplot` code chunk.

Two asides:

1. Whenever you start a new code chunk, it is best practices to leave an empty line above and below it or you might experience some unintended errors. Press **Return** at the end of line 322 and you should be good to go.
2. When you provide a label for a code chunk, you will run into issues if you have spaces in these (e.g., the `Dennys and Laquinta Scatterplot` code chunk). One way around this is to use underscores `_` instead of spaces ` ` in code chunk labels.
